import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createRuntime} from '../dist/index.js';
// Generated by compiling the public-domain C++ reference at the pinned Toast
// revision aecc51e9449c6e7c95272f0f044b5ba38948459e (g++ -O0), not by this port.
test('1D–4D simplex noise agrees with independent pinned C++ vectors',async()=>{
 const vectors=JSON.parse(await readFile(new URL('./helpers/noise-vectors.json',import.meta.url),'utf8'));
 const r=await createRuntime({profile:'toaststunt'});
 try{
  for(const {input,expected} of vectors){const coordinates=input.map(x=>Number.isInteger(x)?x+'.0':String(x)).join(',');const result=r.run(`return simplex_noise({${coordinates}});`);assert.equal(result.status,'completed');assert.ok(Math.abs(result.value.value-expected)<1e-12,JSON.stringify({input,expected,actual:result.value.value}));}
  for(const source of ['simplex_noise({})','simplex_noise({1})','simplex_noise({1.0,2.0,3.0,4.0,5.0})','simplex_noise({1e20})'])assert.equal(r.run('return '+source+';').status,'runtime-error');
 }finally{r.dispose();}
});
